export const VENUES = [
  {
    id: 'v1',
    name: 'Mamasita',
    emoji: '🌮',
    cuisine: 'Mexican',
    distance: '0.4km',
    price: '$',
    tags: ['Tacos', 'Bar', 'Lively'],
    bg_color: '#FF6B6B',
  },
  {
    id: 'v2',
    name: 'Tipo 00',
    emoji: '🍝',
    cuisine: 'Italian',
    distance: '0.9km',
    price: '$',
    tags: ['Pasta', 'Wine', 'Cozy'],
    bg_color: '#F59E0B',
  },
  {
    id: 'v3',
    name: 'Kisume',
    emoji: '🍣',
    cuisine: 'Japanese',
    distance: '0.8km',
    price: '$$',
    tags: ['Sushi', 'Omakase'],
    bg_color: '#3B82F6',
  },
  {
    id: 'v4',
    name: 'Longrain',
    emoji: '🍜',
    cuisine: 'Thai',
    distance: '0.6km',
    price: '$',
    tags: ['Noodles', 'Cocktails'],
    bg_color: '#14B8A6',
  },
  {
    id: 'v5',
    name: 'Gimlet',
    emoji: '🥩',
    cuisine: 'Australian',
    distance: '0.5km',
    price: '$$',
    tags: ['Fine dining', 'Wine'],
    bg_color: '#8B5CF6',
  },
  {
    id: 'v6',
    name: 'Anchovy',
    emoji: '🐟',
    cuisine: 'Vietnamese',
    distance: '1.1km',
    price: '$',
    tags: ['Modern', 'Share plates'],
    bg_color: '#EC4899',
  },
  {
    id: 'v7',
    name: 'Lee Ho Fook',
    emoji: '🥟',
    cuisine: 'Chinese',
    distance: '0.7km',
    price: '$',
    tags: ['Dumplings', 'Lively'],
    bg_color: '#22C55E',
  },
  {
    id: 'v8',
    name: 'Supernormal',
    emoji: '🦞',
    cuisine: 'Asian fusion',
    distance: '0.3km',
    price: '$',
    tags: ['Lobster roll', 'Bar'],
    bg_color: '#6B7280',
  },
]
